Algoritmo "exercicio2"

Var
// Seção de Declarações das variáveis 
  soma, numero1, numero2:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
       escreva(" escreva o primeiro numero: ")
       leia(numero1)
       escreva(" escreva o segundo numero: ")
       leia(numero2)
       soma<-numero1 + numero2
       escreva(" resultado " , soma)
Fimalgoritimo