Algoritmo "exercicio12"

Var
     idade:real




Inicio
     escreva(" digite sua idade: " )
     leia(idade)
se(idade<=12)entao
     escreva(" criança ")
senao
se(idade=13) e (idade<17)entao
     escreva(" adolescente ")
senao
se(idade>18) e (idade<59)entao
     escreva(" adulto ")
senao
se(idade>59)entao
    escreva(" idoso ")
    fimse
    fimse
    fimse
    fimse



Fimalgoritmo