Algoritmo "EXERCICIO16"

Var
    l1 , l2 , l3 :real


Inicio
     escreva(" digite o valor do l1: ")
     leia(l1)
     escreva(" digite o valor do l2: ")
     leia(l2)
     escreva(" digite o valor do l3: ")
     leia(l3)
se(l1 + l2>l3)entao
     escreva(" a soma dos dois lados formam um triangulo. ")
senao
se(l1 + l2<l3)entao
     escreva(" nao é possível formar um triangulo. ")
     fimse
     fimse

Fimalgoritmo